# Use root/example as user/password credentials
version: '3.3'

services:

  db:
    image: mysql:5.7.30
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-root-secret-pw
      MYSQL_DATABASE: stock_db
      MYSQL_USER: stock
      MYSQL_PASSWORD: ywJjDh1jhdQHmPbtjxjz
    volumes:
      - ../db_data:/var/lib/mysql
    ports:
      - 3306:3306
      
# volumes:
#     db_data: {}